version: '3.4'

services:
  db:
    image: postgresql
    build: .
    hostname: db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports: 
     - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=banking